// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_0pZ6AzNn004BTC59TZBWl4cQIAKIyCQ',
    appId: '1:153802095426:web:687780d03f8dc7192226db',
    messagingSenderId: '153802095426',
    projectId: 'bamtol-43262',
    authDomain: 'bamtol-43262.firebaseapp.com',
    storageBucket: 'bamtol-43262.firebasestorage.app',
    measurementId: 'G-EJ01SWXRJH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDI6WQNwUQPC6JLFMz8yvqiNqjIocO7tcA',
    appId: '1:153802095426:android:7ba6a17c8c3c6d1e2226db',
    messagingSenderId: '153802095426',
    projectId: 'bamtol-43262',
    storageBucket: 'bamtol-43262.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL3aEo_nhb9xSLM30lOUACTUNEPVZUaDM',
    appId: '1:153802095426:ios:7b90f5aa99ff8f772226db',
    messagingSenderId: '153802095426',
    projectId: 'bamtol-43262',
    storageBucket: 'bamtol-43262.firebasestorage.app',
    iosBundleId: 'com.example.bamtol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL3aEo_nhb9xSLM30lOUACTUNEPVZUaDM',
    appId: '1:153802095426:ios:7b90f5aa99ff8f772226db',
    messagingSenderId: '153802095426',
    projectId: 'bamtol-43262',
    storageBucket: 'bamtol-43262.firebasestorage.app',
    iosBundleId: 'com.example.bamtol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_0pZ6AzNn004BTC59TZBWl4cQIAKIyCQ',
    appId: '1:153802095426:web:8097221fba09cb632226db',
    messagingSenderId: '153802095426',
    projectId: 'bamtol-43262',
    authDomain: 'bamtol-43262.firebaseapp.com',
    storageBucket: 'bamtol-43262.firebasestorage.app',
    measurementId: 'G-M7Q32KKRHK',
  );
}
